markdown: kramdown
title: FeatherBB
email: admin@featherbb.org
description: "A simple and lightweight new generation forum system."
baseurl: "http://featherbb.org"
url: "http://featherbb.org"
twitter_username: FeatherBB_forum
kramdown:
  input: GFM

collections:
  docs:
    output: true
